services:
  # vocapedia-backend:
  #   container_name: vocapedia-backend
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./backend:/app
  #     - ./backend/config.yaml:/app/config.yaml
  #   ports:
  #     - "3000:3000"
  #     - "50051:50051"
  #   environment:
  #     - MIGRATE=true
  #     - SEED=true
  #   depends_on:
  #     - vocapedia-psql
  #   networks:
  #     - vocapedia

  vocapedia-psql:
    container_name: vocapedia-psql
    image: "postgres:14.6"
    volumes:
      - vocapedia_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vocapedia
      POSTGRES_PASSWORD: vocapedia
      POSTGRES_DB: vocapedia
    networks:
      - vocapedia

networks:
  vocapedia:
    name: vocapedia_network
    driver: bridge

volumes:
  vocapedia_pgdata:
    external: false
