services:
  vocapedia-backend:
    container_name: vocapedia-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - ./backend/config.yaml:/app/config.yaml
      - ./backend/.air.toml:/app/.air.toml
    ports:
      - "3000:3000"
      - "50051:50051"
    depends_on:
      - vocapedia-psql
      - vocapedia-redis
    networks:
      - vocapedia

  vocapedia-psql:
    container_name: vocapedia-psql
    image: "postgres:14.6"
    volumes:
      - vocapedia_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vocapedia
      POSTGRES_PASSWORD: vocapedia
      POSTGRES_DB: vocapedia
    networks:
      - vocapedia
  vocapedia-redis:
    container_name: vocapedia-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - vocapedia
    restart: unless-stopped
    
networks:
  vocapedia:
    name: vocapedia_network
    driver: bridge

volumes:
  vocapedia_pgdata:
    external: false
  redis-data:
    external: false
