host:
port: 3000
grpc_port: 50051
env: production
base_url: http://localhost:8080
front_base_url: http://localhost:8080
jwt_secret: vocapedia
jwt_expire: 720 # time in hours
jwt_issuer: vocapedia
totp_issuer: vocapedia
admin_email: vocapedia.space@gmail.com
admin_username: vocapedia
admin_name: vocapedia
admin_biography: Welcome to world of words!

smtp:
  from: vocapedia.space@gmail.com
  host: smtp.gmail.com
  password: ddef kfof cpte rwge
  port: 587

database:
  host: vocapedia-psql
  port: 5432
  name: vocapedia
  user: vocapedia
  password: vocapedia
  sslmode: disable

meilisearch:
  host: http://meilisearch:7700
  api_key: vocapedia
  index: chapters
  timeout: 10

redis:
  host: vocapedia-redis
  port: 6379
  password:
  db: 0

allow_methods:
  - GET
  - POST
  - PUT
  - PATCH
  - DELETE
  - OPTIONS

allow_headers:
  - Content-Type
  - Authorization
  - X-HASH
  - sentry-trace

allow_origins:
  - "*"
