# important: alpine image is not compatible because of the cgo
FROM golang:1.23

WORKDIR /app

COPY go.mod go.sum ./

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/go/pkg/sumdb \
    go mod download

COPY . .


RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/go/pkg/sumdb \
    go install github.com/cosmtrek/air@v1.44.0


COPY ./config.yaml ./config.yaml
COPY ./.air.toml ./.air.toml

ENV CGO_ENABLED=1

CMD ["air", "-c", ".air.toml"]
